### ISSUE TITLE
Exception has occurred. RangeError (RangeError (byteOffset): Invalid value: Not in inclusive range 0..5: 7)

### ISSUE THREAD

**Issue by lamynespl** [adamlofts/mysql1_dart#129]
Running the code as is I get the error:

var result = await conn.query(
      'insert into users (name, email, age) values (?, ?, ?)',
      ['Bob', 'bob@bob.com', 25]);
  // ignore: avoid_print
  print('Inserted row id=${result.insertId}');

Exception has occurred.
RangeError (RangeError (byteOffset): Invalid value: Not in inclusive range 0..5: 7)

I can run it if I don't use the question marks and just use the data in it's place.

Sort of blocked.

**Comment by SavageTee** [comment]
i get the same error calling multiple STORED PROCEDURES 

`for(x = 0; x<100; x++){
 var stor1 = await Connection.query("CALL Flutter_ServerId(?);",['3',]);
 var stor2 = await Connection.query("CALL Flutter_FromTo(?);",['3',]);
}`

> E/flutter (24143): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: RangeError (byteOffset): Invalid value: Not in inclusive range 0..5: 7
E/flutter (24143): #0      _ByteDataView.getUint16 (dart:typed_data-patch/typed_data_patch.dart:4822:7)
E/flutter (24143): #1      Buffer.readUint16 (package:mysql1/src/buffer.dart:240:24)
E/flutter (24143): #2      new PrepareOkPacket (package:mysql1/src/prepared_statements/prepare_ok_packet.dart:20:30)
E/flutter (24143): #3      Handler.checkResponse (package:mysql1/src/handlers/handler.dart:68:24)
E/flutter (24143): #4      PrepareHandler.processResponse (package:mysql1/src/prepared_statements/prepare_handler.dart:45:18)
E/flutter (24143): #5      ReqRespConnection._handleData (package:mysql1/src/single_connection.dart:349:32)
E/flutter (24143): #6      ReqRespConnection._handleHeader (package:mysql1/src/single_connection.dart:318:13)
E/flutter (24143): <asynchronous suspension>
E/flutter (24143): #7      ReqRespConnection._readPacket (package:mysql1/src/single_connection.dart:303:7)
E/flutter (24143): <asynchronous suspension>

most probably its a bug

**Comment by dongri727** [comment]
I got exactly same error with trying the example code on pub.dev,
 my conditions: m1mac, flutter3, MySql8
