### ISSUE TITLE
facing the error that my ip is not allowed to connect with server how can i resolve this error ?

### ISSUE THREAD

**Issue by DhruvAkshay** [adamlofts/mysql1_dart#134]
/flutter (27836): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Error 1130 (ost '): 192.168.43.144' is not allowed to connect to this MySQL server
E/flutter (27836): #0      Handler.checkResponse (package:mysql1/src/handlers/handler.dart:77:7)
E/flutter (27836): #1      HandshakeHandler.processResponse (package:mysql1/src/auth/handshake_handler.dart:129:5)
E/flutter (27836): #2      ReqRespConnection._handleData (package:mysql1/src/single_connection.dart:349:32)
E/flutter (27836): #3      ReqRespConnection._handleHeader (package:mysql1/src/single_connection.dart:318:13)
E/flutter (27836): <asynchronous suspension>
E/flutter (27836): #4      ReqRespConnection._readPacket (package:mysql1/src/single_connection.dart:303:7)
E/flutter (27836): <asynchronous suspension>
E/flutter (27836):

**Comment by safwanyp** [comment]
I had received this error when working on a personal project and it was caused when the app wasn't able to connect to the internet.

Have you added internet permissions in your XML file? Can your emulator access the internet? Let me know if this helped
