### ISSUE TITLE
Unsupported operation RawSocket

### ISSUE THREAD

**Issue by princesanjivy** [adamlofts/mysql1_dart#67]
I get this error, also I'm on Flutter Web and OS Ubuntu.

**Error: Unsupported operation: RawSocket constructor
at Object.throw_ [as throw]
    at Function.connect** 

I googled this issue and I found out that RawSocket class doesn't have a connect method.
<a href="https://stackoverflow.com/questions/54933232/exception-unsupported-operation-rawsocket-constructor-dart-with-sqljocky5-2">Stackoverflow</a>

Any solutions would be really helpful!

**Comment by rolong13** [comment]
I got a similar message, Error: Unsupported operation: RawSocket constructor
In my case, it appears it has to do with a MySQL query I am trying to run using the MySQL1 package, latest version as of tis writing.

But it appears it only fails when try to compile the web, because the code works fine when using the android emulator...

So it looks like this functionality needs to be added to MySQL1 as soon as possible since Flutter 2.0 has open the flood gates and web is  stable.

Looking at the code today, but not sure how far I will get if at all, still in the process of learning dart...:)

**Comment by rolong13** [comment]
Here is the dump of the error, looks like the problem is in the buffered_socket.dart file, I took a look, but still looking like a foreign language to me :(,  really hope someone can help soon...:)

Launching lib\main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:53856/zMb4gCgCJhg=/ws
Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Connecting to VM Service at ws://127.0.0.1:53856/zMb4gCgCJhg=/ws
this sucks..
Error: Unsupported operation: RawSocket constructor
    at Object.throw_ [as throw] (http://localhost:53826/dart_sdk.js:5334:11)
    at Function.connect (http://localhost:53826/dart_sdk.js:58946:17)
    at defaultSocketFactory (http://localhost:53826/packages/mysql1/src/buffered_socket.dart.lib.js:115:27)
    at connect (http://localhost:53826/packages/mysql1/src/buffered_socket.dart.lib.js:125:42)
    at connect.next (<anonymous>)
    at runBody (http://localhost:53826/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:53826/dart_sdk.js:39083:7)
    at Function.connect (http://localhost:53826/packages/mysql1/src/buffered_socket.dart.lib.js:123:20)
    at connect (http://localhost:53826/packages/mysql1/src/single_connection.dart.lib.js:258:60)
    at connect.next (<anonymous>)
    at runBody (http://localhost:53826/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:53826/dart_sdk.js:39083:7)
    at Function.connect (http://localhost:53826/packages/mysql1/src/single_connection.dart.lib.js:252:20)
    at getConnection (http://localhost:53826/packages/flutter_2_mysql_test/mysql.dart.lib.js:31:56)
    at getConnection.next (<anonymous>)
    at runBody (http://localhost:53826/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:53826/dart_sdk.js:39083:7)
    at mysql.Mysql.new.getConnection (http://localhost:53826/packages/flutter_2_mysql_test/mysql.dart.lib.js:29:20)
    at _getWeight (http://localhost:53826/packages/flutter_2_mysql_test/main.dart.lib.js:35:10)
    at main$ (http://localhost:53826/packages/flutter_2_mysql_test/main.dart.lib.js:46:5)
    at main (http://localhost:53826/web_entrypoint.dart.lib.js:46:29)
    at main.next (<anonymous>)
    at http://localhost:53826/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:53826/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53826/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:53826/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:53826/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:53826/dart_sdk.js:34315:23)
    at http://localhost:53826/dart_sdk.js:33526:46
    at _RootZone.runUnary (http://localhost:53826/dart_sdk.js:38889:58)
    at _FutureListener.then.handleValue (http://localhost:53826/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:53826/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:53826/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:53826/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53826/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:53826/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:53826/dart_sdk.js:39182:13)
    at http://localhost:53826/dart_sdk.js:34689:9

**Comment by evetechsolutions** [comment]
Any news on this issue?

**Comment by rodrigo-ehlers** [comment]
I'm having the same issue, running great on Android Emulator, failing on Web. Hope MySQL1 get Web ASAP. For now, to my code work as it should, I need to write the querys on PHP and access the .php file from my server with http.dart dependecy. It works, but is far from a good solution.

**Comment by MahmoodAliL** [comment]
<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDgyMzkzNDA0NA==" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDgyMzkzNDA0NA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDgyMzkzNDA0NA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-823934044" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container js-comment timeline-comment--caret reorderable-task-lists" data-body-version="e7e5853187b08816c96e116d82c9affc76e4598339c227afa5f09435018e4a32" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists disabled="" sortable="" style="box-sizing: border-box;">Any news on this issue?</task-lists></div></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MjY2NzI5Nw==" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MjY2NzI5Nw==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0MjY2NzI5Nw==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><br class="Apple-interchange-newline">

</div></div>

**Comment by adamlofts** [comment]
This package opens a socket to the database. The web platform does not support sockets and so this package does not work on flutter web.
